services:
  shelfmark:
    image: ghcr.io/calibrain/shelfmark-lite:dev
    container_name: shelfmark
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      DOCKERMODE: true
      CALIBRE_WEB_URL: "http://localhost:${BOOKLORE_PORT}"
      ONBOARDING: false
      SEARCH_MODE: "universal"
      IRC_SERVER: "irc.irchighway.net"
      IRC_PORT: 6669
      IRC_CHANNEL: "ebooks"
      IRC_NICK: "wasylews"
      IRC_SEARCH_BOT: "search"
      IRC_USE_TLS: false
      OPENLIBRARY_ENABLED: true
    ports:
      - "${SHELFMARK_PORT}:${SHELFMARK_PORT}"
    networks:
      - books
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_DIR}:/books # Default destination for book downloads
      - ${CONFIG_DIR}/shelfmark:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - ${DOWNLOADS_DIR}:/downloads

networks:
  books:
    external: true
