---
- name: Ensure adguard config directory exists
  ansible.builtin.file:
    path: "{{ adguard.config_dir }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0750"

- name: Render adguard config file
  ansible.builtin.template:
    src: templates/adguard.yml.j2
    dest: "{{ adguard.config_dir }}/AdGuardHome.yaml"
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0750"
  tags: config

- name: Ensure adguard work directory exists
  ansible.builtin.file:
    path: "{{ adguard.work_dir }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0700"

- name: Start AdguardHome container
  community.docker.docker_container:
    name: "{{ adguard.container_name }}"
    image: "{{ adguard.image }}"
    volumes:
      - "{{ adguard.config_dir }}:/opt/adguardhome/conf"
      - "{{ adguard.work_dir }}:/opt/adguardhome/work"
    restart_policy: unless-stopped
    networks:
      - name: proxy
    state: started
    pull: always
    expose:
      - "{{ adguard.port }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
