---
# Defaults for Caddy reverse proxy
caddy:
  network: proxy
  config_dir: "{{ config_dir }}/caddy"
  labels: {
    "caddy_98": "adguard.{{ inventory_hostname }}",
    "caddy_98.reverse_proxy": "adguard:{{ adguard.port }}",
    "caddy_98.tls": "internal",

    "caddy_99": "booklore.{{ inventory_hostname }}",
    "caddy_99.reverse_proxy": "booklore:{{ booklore.port }}",
    "caddy_99.tls": "internal",

    "caddy_100": "shelfmark.{{ inventory_hostname }}",
    "caddy_100.reverse_proxy": "shelfmark:{{ shelfmark.port }}",
    "caddy_100.tls": "internal",
  }
