---
# Defaults for Shelfmark service
shelfmark:
  image: ghcr.io/calibrain/shelfmark-lite:v1.3.10
  container_name: shelfmark
  port: 8084
irc_server: irc.irchighway.net
irc_port: 6669
irc_channel: ebooks
irc_search_bot: search
