---
# Defaults for MariaDB service
mariadb:
  image: lscr.io/linuxserver/mariadb:11.8.8
  container_name: mariadb
  config_dir: "{{ config_dir }}/mariadb"
  port: 3306
  db:
    name: booklore
    user: booklore
