---
- name: Ensure mariadb config directory exists
  ansible.builtin.file:
    path: "{{ mariadb.config_dir }}"
    state: directory
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: "0750"

- name: Start mariadb container
  community.docker.docker_container:
    name: "{{ mariadb.container_name }}"
    image: "{{ mariadb.image }}"
    env:
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ secrets.db.root_password }}"
      MYSQL_DATABASE: "{{ mariadb.db.name }}"
      MYSQL_USER: "{{ mariadb.db.user }}"
      MYSQL_PASSWORD: "{{ secrets.db.password }}"
    volumes:
      - "{{ mariadb.config_dir }}:/config"
    expose:
      - "{{ mariadb.port }}"
    networks:
      - name: proxy
    restart_policy: unless-stopped
    state: started
    pull: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -u$MYSQL_USER -p$MYSQL_PASSWORD || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 30s
  no_log: true
