---
# Defaults for audiobookshelf service
audiobookshelf:
  image: advplyr/audiobookshelf:2.36.0
  config_dir: "{{ config_dir }}/audiobookshelf"
  work_dir: "{{ services_dir }}/audiobookshelf"
  container_name: audiobookshelf
  port: 80
