all:
  children:
    dev:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        library_dir: "{{ playbook_dir }}/build/library"
        downloads_dir: "{{ playbook_dir }}/build/bookdrop"
        services_dir: "{{ playbook_dir }}/build/services"
        config_dir: "{{ playbook_dir }}/build/services/config"
        