all:
  children:
    pi:
      hosts:
        pi.lan:
          ansible_host: 192.168.0.X # replace with your Raspberry Pi address
      vars:
        services_dir: "{{ ansible_facts['user_dir'] }}/services"
        library_dir: "{{ ansible_facts['user_dir'] }}/library"
        downloads_dir: "{{ ansible_facts['user_dir'] }}/bookdrop"
        config_dir: "{{ ansible_facts['user_dir'] }}/services/config"