all:
  children:
    pi:
      hosts:
        192.168.0.112: {}
      vars:
        services_dir: /home/wasylews/services
        library_dir: /home/wasylews/library
        downloads_dir: /home/wasylews/bookdrop
