---
- name: Ensure library directory exists
  ansible.builtin.file:
    path: "{{ library_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ puid }}"
    group: "{{ pgid }}"

- name: Ensure downloads directory exists
  ansible.builtin.file:
    path: "{{ downloads_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ puid }}"
    group: "{{ pgid }}"

- name: Ensure services directory exists
  ansible.builtin.file:
    path: "{{ services_dir }}"
    state: directory
    mode: "0755"

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ config_dir }}"
    state: directory
    mode: "0755"
