---
# Defaults for AdguardHome service
adguard:
  image: adguard/adguardhome:latest
  config_dir: "{{ config_dir }}/adguard"
  work_dir: "{{ services_dir }}/adguard"
  container_name: adguard
  port: 80
